/*
 * Fava - OpenApi Gateway - DNS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopinto

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
	"strings"
)

// Linger please
var (
	_ _context.Context
)

type ZoneApi interface {

	/*
	 * DnsApiZonesDelete Deletes a DNS zone from the passed provider
	 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return ApiDnsApiZonesDeleteRequest
	 */
	DnsApiZonesDelete(ctx _context.Context) ApiDnsApiZonesDeleteRequest

	/*
	 * DnsApiZonesDeleteExecute executes the request
	 */
	DnsApiZonesDeleteExecute(r ApiDnsApiZonesDeleteRequest) (*_nethttp.Response, error)

	/*
	 * DnsApiZonesGet Retrieves the DNS zones assigned to the account
	 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return ApiDnsApiZonesGetRequest
	 */
	DnsApiZonesGet(ctx _context.Context) ApiDnsApiZonesGetRequest

	/*
	 * DnsApiZonesGetExecute executes the request
	 * @return []Zone
	 */
	DnsApiZonesGetExecute(r ApiDnsApiZonesGetRequest) ([]Zone, *_nethttp.Response, error)

	/*
	 * DnsApiZonesPost Creates a new DNS zone
	 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return ApiDnsApiZonesPostRequest
	 */
	DnsApiZonesPost(ctx _context.Context) ApiDnsApiZonesPostRequest

	/*
	 * DnsApiZonesPostExecute executes the request
	 * @return Zone
	 */
	DnsApiZonesPostExecute(r ApiDnsApiZonesPostRequest) (Zone, *_nethttp.Response, error)

	/*
	 * DnsApiZonesZoneGet Loads the specified DNS zone
	 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param zone The name of the zone to query.
	 * @return ApiDnsApiZonesZoneGetRequest
	 */
	DnsApiZonesZoneGet(ctx _context.Context, zone string) ApiDnsApiZonesZoneGetRequest

	/*
	 * DnsApiZonesZoneGetExecute executes the request
	 * @return Zone
	 */
	DnsApiZonesZoneGetExecute(r ApiDnsApiZonesZoneGetRequest) (Zone, *_nethttp.Response, error)
}

// ZoneApiService ZoneApi service
type ZoneApiService service

type ApiDnsApiZonesDeleteRequest struct {
	ctx         _context.Context
	ApiService  ZoneApi
	name        *string
	xApiOptions *string
}

func (r ApiDnsApiZonesDeleteRequest) Name(name string) ApiDnsApiZonesDeleteRequest {
	r.name = &name
	return r
}
func (r ApiDnsApiZonesDeleteRequest) XApiOptions(xApiOptions string) ApiDnsApiZonesDeleteRequest {
	r.xApiOptions = &xApiOptions
	return r
}

func (r ApiDnsApiZonesDeleteRequest) Execute() (*_nethttp.Response, error) {
	return r.ApiService.DnsApiZonesDeleteExecute(r)
}

/*
 * DnsApiZonesDelete Deletes a DNS zone from the passed provider
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiDnsApiZonesDeleteRequest
 */
func (a *ZoneApiService) DnsApiZonesDelete(ctx _context.Context) ApiDnsApiZonesDeleteRequest {
	return ApiDnsApiZonesDeleteRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

/*
 * Execute executes the request
 */
func (a *ZoneApiService) DnsApiZonesDeleteExecute(r ApiDnsApiZonesDeleteRequest) (*_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodDelete
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ZoneApiService.DnsApiZonesDelete")
	if err != nil {
		return nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/dns/api/Zones"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.name == nil {
		return nil, reportError("name is required and must be specified")
	}
	if r.xApiOptions == nil {
		return nil, reportError("xApiOptions is required and must be specified")
	}

	localVarQueryParams.Add("Name", parameterToString(*r.name, ""))
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["x-api-options"] = parameterToString(*r.xApiOptions, "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiDnsApiZonesGetRequest struct {
	ctx         _context.Context
	ApiService  ZoneApi
	xApiOptions *string
}

func (r ApiDnsApiZonesGetRequest) XApiOptions(xApiOptions string) ApiDnsApiZonesGetRequest {
	r.xApiOptions = &xApiOptions
	return r
}

func (r ApiDnsApiZonesGetRequest) Execute() ([]Zone, *_nethttp.Response, error) {
	return r.ApiService.DnsApiZonesGetExecute(r)
}

/*
 * DnsApiZonesGet Retrieves the DNS zones assigned to the account
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiDnsApiZonesGetRequest
 */
func (a *ZoneApiService) DnsApiZonesGet(ctx _context.Context) ApiDnsApiZonesGetRequest {
	return ApiDnsApiZonesGetRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

/*
 * Execute executes the request
 * @return []Zone
 */
func (a *ZoneApiService) DnsApiZonesGetExecute(r ApiDnsApiZonesGetRequest) ([]Zone, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  []Zone
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ZoneApiService.DnsApiZonesGet")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/dns/api/Zones"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.xApiOptions == nil {
		return localVarReturnValue, nil, reportError("xApiOptions is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["x-api-options"] = parameterToString(*r.xApiOptions, "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDnsApiZonesPostRequest struct {
	ctx                    _context.Context
	ApiService             ZoneApi
	xApiOptions            *string
	createZoneRequestModel *CreateZoneRequestModel
}

func (r ApiDnsApiZonesPostRequest) XApiOptions(xApiOptions string) ApiDnsApiZonesPostRequest {
	r.xApiOptions = &xApiOptions
	return r
}
func (r ApiDnsApiZonesPostRequest) CreateZoneRequestModel(createZoneRequestModel CreateZoneRequestModel) ApiDnsApiZonesPostRequest {
	r.createZoneRequestModel = &createZoneRequestModel
	return r
}

func (r ApiDnsApiZonesPostRequest) Execute() (Zone, *_nethttp.Response, error) {
	return r.ApiService.DnsApiZonesPostExecute(r)
}

/*
 * DnsApiZonesPost Creates a new DNS zone
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiDnsApiZonesPostRequest
 */
func (a *ZoneApiService) DnsApiZonesPost(ctx _context.Context) ApiDnsApiZonesPostRequest {
	return ApiDnsApiZonesPostRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

/*
 * Execute executes the request
 * @return Zone
 */
func (a *ZoneApiService) DnsApiZonesPostExecute(r ApiDnsApiZonesPostRequest) (Zone, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodPost
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  Zone
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ZoneApiService.DnsApiZonesPost")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/dns/api/Zones"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.xApiOptions == nil {
		return localVarReturnValue, nil, reportError("xApiOptions is required and must be specified")
	}
	if r.createZoneRequestModel == nil {
		return localVarReturnValue, nil, reportError("createZoneRequestModel is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json", "text/json", "application/_*+json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["x-api-options"] = parameterToString(*r.xApiOptions, "")
	// body params
	localVarPostBody = r.createZoneRequestModel
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDnsApiZonesZoneGetRequest struct {
	ctx         _context.Context
	ApiService  ZoneApi
	zone        string
	xApiOptions *string
}

func (r ApiDnsApiZonesZoneGetRequest) XApiOptions(xApiOptions string) ApiDnsApiZonesZoneGetRequest {
	r.xApiOptions = &xApiOptions
	return r
}

func (r ApiDnsApiZonesZoneGetRequest) Execute() (Zone, *_nethttp.Response, error) {
	return r.ApiService.DnsApiZonesZoneGetExecute(r)
}

/*
 * DnsApiZonesZoneGet Loads the specified DNS zone
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param zone The name of the zone to query.
 * @return ApiDnsApiZonesZoneGetRequest
 */
func (a *ZoneApiService) DnsApiZonesZoneGet(ctx _context.Context, zone string) ApiDnsApiZonesZoneGetRequest {
	return ApiDnsApiZonesZoneGetRequest{
		ApiService: a,
		ctx:        ctx,
		zone:       zone,
	}
}

/*
 * Execute executes the request
 * @return Zone
 */
func (a *ZoneApiService) DnsApiZonesZoneGetExecute(r ApiDnsApiZonesZoneGetRequest) (Zone, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  Zone
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "ZoneApiService.DnsApiZonesZoneGet")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/dns/api/Zones/{zone}"
	localVarPath = strings.Replace(localVarPath, "{"+"zone"+"}", _neturl.PathEscape(parameterToString(r.zone, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.xApiOptions == nil {
		return localVarReturnValue, nil, reportError("xApiOptions is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain", "application/json", "text/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	localVarHeaderParams["x-api-options"] = parameterToString(*r.xApiOptions, "")
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
