/*
 * Pinto - OpenApi Gateway - DNS
 *
 * <h1>Additional info</h1> <h2><a href=\"/nexus-info\">Nexus Info (DNS - CloudProviders)</h2></a>  <h2><a href=\"/markdown/OPENAPIGATEWAY-USAGE.MD\">OPENAPIGATEWAY-USAGE.MD</h2></a> <h2><a href=\"/markdown/CHANGELOG.md\">CHANGELOG.md</h2></a> <h2><a href=\"/markdown/version.md\">version.md</h2></a>
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopinto

import (
	"encoding/json"
)

// CreateZoneRequestModel struct for CreateZoneRequestModel
type CreateZoneRequestModel struct {
	Provider    string         `json:"provider"`
	Environment NullableString `json:"environment,omitempty"`
	Name        string         `json:"name"`
}

// NewCreateZoneRequestModel instantiates a new CreateZoneRequestModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateZoneRequestModel(provider string, name string) *CreateZoneRequestModel {
	this := CreateZoneRequestModel{}
	this.Provider = provider
	this.Name = name
	return &this
}

// NewCreateZoneRequestModelWithDefaults instantiates a new CreateZoneRequestModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateZoneRequestModelWithDefaults() *CreateZoneRequestModel {
	this := CreateZoneRequestModel{}
	return &this
}

// GetProvider returns the Provider field value
func (o *CreateZoneRequestModel) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *CreateZoneRequestModel) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *CreateZoneRequestModel) SetProvider(v string) {
	o.Provider = v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateZoneRequestModel) GetEnvironment() string {
	if o == nil || o.Environment.Get() == nil {
		var ret string
		return ret
	}
	return *o.Environment.Get()
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateZoneRequestModel) GetEnvironmentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Environment.Get(), o.Environment.IsSet()
}

// HasEnvironment returns a boolean if a field has been set.
func (o *CreateZoneRequestModel) HasEnvironment() bool {
	if o != nil && o.Environment.IsSet() {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given NullableString and assigns it to the Environment field.
func (o *CreateZoneRequestModel) SetEnvironment(v string) {
	o.Environment.Set(&v)
}

// SetEnvironmentNil sets the value for Environment to be an explicit nil
func (o *CreateZoneRequestModel) SetEnvironmentNil() {
	o.Environment.Set(nil)
}

// UnsetEnvironment ensures that no value is present for Environment, not even an explicit nil
func (o *CreateZoneRequestModel) UnsetEnvironment() {
	o.Environment.Unset()
}

// GetName returns the Name field value
func (o *CreateZoneRequestModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateZoneRequestModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateZoneRequestModel) SetName(v string) {
	o.Name = v
}

func (o CreateZoneRequestModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["provider"] = o.Provider
	}
	if o.Environment.IsSet() {
		toSerialize["environment"] = o.Environment.Get()
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCreateZoneRequestModel struct {
	value *CreateZoneRequestModel
	isSet bool
}

func (v NullableCreateZoneRequestModel) Get() *CreateZoneRequestModel {
	return v.value
}

func (v *NullableCreateZoneRequestModel) Set(val *CreateZoneRequestModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateZoneRequestModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateZoneRequestModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateZoneRequestModel(val *CreateZoneRequestModel) *NullableCreateZoneRequestModel {
	return &NullableCreateZoneRequestModel{value: val, isSet: true}
}

func (v NullableCreateZoneRequestModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateZoneRequestModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
