/*
 * Fava - OpenApi Gateway - DNS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopinto

import (
	"encoding/json"
)

// CreateZoneRequestModel struct for CreateZoneRequestModel
type CreateZoneRequestModel struct {
	// Name of the DNS zone to create.
	Name string `json:"name"`
}

// NewCreateZoneRequestModel instantiates a new CreateZoneRequestModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateZoneRequestModel(name string) *CreateZoneRequestModel {
	this := CreateZoneRequestModel{}
	this.Name = name
	return &this
}

// NewCreateZoneRequestModelWithDefaults instantiates a new CreateZoneRequestModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateZoneRequestModelWithDefaults() *CreateZoneRequestModel {
	this := CreateZoneRequestModel{}
	return &this
}

// GetName returns the Name field value
func (o *CreateZoneRequestModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateZoneRequestModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateZoneRequestModel) SetName(v string) {
	o.Name = v
}

func (o CreateZoneRequestModel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCreateZoneRequestModel struct {
	value *CreateZoneRequestModel
	isSet bool
}

func (v NullableCreateZoneRequestModel) Get() *CreateZoneRequestModel {
	return v.value
}

func (v *NullableCreateZoneRequestModel) Set(val *CreateZoneRequestModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateZoneRequestModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateZoneRequestModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateZoneRequestModel(val *CreateZoneRequestModel) *NullableCreateZoneRequestModel {
	return &NullableCreateZoneRequestModel{value: val, isSet: true}
}

func (v NullableCreateZoneRequestModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateZoneRequestModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
