/*
 * Fava - OpenApi Gateway - DNS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package gopinto

import (
	"encoding/json"
	"fmt"
)

// RecordClass Resource record classes  as defined in  <see href=\"https://tools.ietf.org/html/rfc1035#section-3.2.4\">rfc1035</see>
type RecordClass string

// List of RecordClass
const (
	RECORDCLASS_IN RecordClass = "IN"
	RECORDCLASS_CS RecordClass = "CS"
	RECORDCLASS_CH RecordClass = "CH"
	RECORDCLASS_HS RecordClass = "HS"
)

var allowedRecordClassEnumValues = []RecordClass{
	"IN",
	"CS",
	"CH",
	"HS",
}

func (v *RecordClass) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RecordClass(value)
	for _, existing := range allowedRecordClassEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RecordClass", value)
}

// NewRecordClassFromValue returns a pointer to a valid RecordClass
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRecordClassFromValue(v string) (*RecordClass, error) {
	ev := RecordClass(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RecordClass: valid values are %v", v, allowedRecordClassEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RecordClass) IsValid() bool {
	for _, existing := range allowedRecordClassEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to RecordClass value
func (v RecordClass) Ptr() *RecordClass {
	return &v
}

type NullableRecordClass struct {
	value *RecordClass
	isSet bool
}

func (v NullableRecordClass) Get() *RecordClass {
	return v.value
}

func (v *NullableRecordClass) Set(val *RecordClass) {
	v.value = val
	v.isSet = true
}

func (v NullableRecordClass) IsSet() bool {
	return v.isSet
}

func (v *NullableRecordClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecordClass(val *RecordClass) *NullableRecordClass {
	return &NullableRecordClass{value: val, isSet: true}
}

func (v NullableRecordClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecordClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
