name: Docker-Publish

on:
  release:
    types:
      - created

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup build env
        run: echo "BUILD_TARGET=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: camao/cert-manager-webhook-project-pinto:latest,camao/cert-manager-webhook-project-pinto:${{ env.BUILD_TARGET }}
